### ISSUE TITLE
Shipping/Billing Address for Klaviyo Profile 

### ISSUE THREAD

**Issue by PepeKey** [FosterCommerce/klaviyoconnect#39]
I have a issue with the syncing of customers.
If no user account is created at checkout process, the profile fields First & Last Name at Klaviyo are empty. 
Is it possible to use the FirstName and LastName from the shipping address?

**Comment by clowerweb** [comment]
https://github.com/FosterCommerce/klaviyoconnect/pull/40

**Comment by sjcallender** [comment]
@PepeKey - We're not comfortable using the Shipping Address's first and last name, since that can often be different than the customer's name associated with the order's email address. However, we should have been using the Billing first and last name for guest customers all along. That's been fixed in [4.0.3](https://github.com/FosterCommerce/klaviyoconnect/releases/tag/4.0.3).
