### ISSUE TITLE
Klaviyo API Changes - June 2022 

### ISSUE THREAD

**Issue by steve-holland** [FosterCommerce/klaviyoconnect#82]
I'm sure you folks are already aware of these changes, but I just wanted to check anyway. Will the announced changes to the Identify API have any impact on the plugin at all?

[Klaviyo June 2022 API Update FAQ](https://cdn.allbound.com/klaviyo-ab/2022/05/19160505/June-2022-API-Update-FAQ-1.pdf)

**Comment by fantasticmachine** [comment]
Hey @steve-holland  :)

I'm working on this plugin now (it'll be fine, don't worry) and have been doing updates to get it Craft 4 compatible. I've only just started so not super familiar with the Identify api yet

I'll take a look at those changes and see if it's going to impact anything. Thanks for drawing it to our attention.

**Comment by steve-holland** [comment]
Hey @fantasticmachine, how's it going.

Now that I know the top people are working on it, consider myself reassured. Cheers for looking into it 👍🏻

**Comment by fantasticmachine** [comment]
Haha!

I've done a quick test and I don't believe that the plugin actually offers the option to update an email address (or any other param) via the Identify API. 

It is, however, possible to update profile information including the email via the Track API. But that first requires the user to be identified.

My test was basic. I first created a list signup form which signed me up to a list and served to identify me to Klaviyo.

I then created another form which posted to the identify API. This had an email and profile[first_name] field.
The result of that was my name getting updated but the email address remained the same.

I then created a form that posted to the Track API and added fields for email, profile[first_name] and profile[last_name]. Using this form allowed me to change both my name and also the email address.

I'm just trying to figure out how to use an ID instead of an email to identify the user so I can test trying to update the email via the Identify API if I use their ID.

**Comment by fantasticmachine** [comment]
So... @steve-holland 

It looks like it is *currently* possible to update the name and phone number via the plugin's Identify controller and this will no longer work from the 13th June. It has never been possible to update the user's email using this controller.

However, it should still be possible to update email, name, phone number and any other data points using the Track controller.

Is there a particular use case you're working with here that you are worried will break?

**Comment by steve-holland** [comment]
@fantasticmachine Thanks for looking. No particular use case, it was more of a general heads up really. We got an email warning us of the changes, so we just didn't want the plugin blowing up on us on the 13th :)

**Comment by steve-holland** [comment]
@fantasticmachine We aren't calling into the controllers directly or anything, we're just using it as standard by listening for the standard events. So I guess it's down to if the plugin's normal operation will be impacted. It may well not.

**Comment by fantasticmachine** [comment]
@steve-holland I've done some work on this and have created some services for updating the identifiers in question. I'm just reviewing the security implications of providing a controller within the plugin or intercepting attempts to update them via the Identify controller.

**Comment by fantasticmachine** [comment]
@steve-holland I have just released v4.0.10 which adds a couple of services and a new controller action for updating Klaviyo profiles.

Note: this is still only compatible with Craft 3. I'm working on testing the Craft 4 version at the moment. These changes will be included in that release when it happens.
