### ISSUE TITLE
Error after update to 4.0.13

### ISSUE THREAD

**Issue by sajjanstha** [FosterCommerce/klaviyoconnect#90]
I get the following error when I go to the plugin settings page(/admin/settings/plugins/klaviyoconnect)

`Call to undefined method craft\helpers\App::parseEnv()`

It happens in both 4.0.12 and 4.0.13.

**Comment by fantasticmachine** [comment]
OK. We could roll back to use the Craft::parseEnv() helper but that's then going to show deprecations for anyone on 3.7.29+

You might want to go back to 4.0.8 of the plugin for now. 

For the record the only real functional difference is that I added some extra controllers and services to allow setting of the user's email address and phone number. This was in response to an API change by Klaviyo.

If you weren't using the plugin to change email addresses and phone numbers on Klaviyo customer records then there's no real need to update.

**Comment by sajjanstha** [comment]
Actually we are trying to update the plugin in response to the API change by Klaviyo. It was addressed in 4.0.10 release so we need at least update it to 4.0.10. 
It looks like we need to update the craft version first before updating this plugin.

**Comment by widewebpro** [comment]
@fantasticmachine For which version of Craft 3.X, have bugs been fixed in this plugin?

**Comment by fantasticmachine** [comment]
@widewebpro If you are on a version of Craft earlier than 3.7.29 then you will need to use 4.0.8 of the KlaviyoConnect plugin.
There isn't really much we can do about that since if we revert the change then the plugin will not work in versions of Craft from 3.7.29 up.

To clarify, the changes made to the plugin for version 4.10 were to provide *additional* methods to the plugin just in case someone was using it to change a Klaviyo email address or telephone number. This was never a documented "feature"  of the plugin anyway and was really an accidental side-effect of the way the plugin is constructed.

So if you are not allowing customers to change their Klaviyo email address or telephone number via the plugin you will be fine with version 4.8.

**Comment by fantasticmachine** [comment]
@sajjanstha @widewebpro 
I've just added a branch which uses the latest version for Craft 3 but also uses `Craft::parseEnv()`. This should mean you can use it on versions of craft earlier than 3.7.29

You can use this version by editing your composer.json file to install from `fix/use-craft-parsenv-for-craft-pre-3-7-29`

Please note that it is a temporary measure and we won't be maintaining this branch going forward but it should mean you can keep using the plugin until you can update Craft to 3.7.29+
